"""
Schema e definições das colunas do estado dos processos.
"""

# Colunas esperadas no DataFrame de estado
COLUNAS_ESTADO = [
    "PROCESSO",
    "VALOR_TOTAL_PROCESSO",
    "TOTAL_ANTECIPACOES",
    "TOTAL_PAGAMENTOS_REGULARES",
    "TOTAL_PAGO_ACUMULADO",
    "SALDO_A_RECEBER",
    "TOTAL_COMISSAO_ANTECIPACOES",
    "TOTAL_COMISSAO_REGULARES",
    "TOTAL_COMISSAO_ACUMULADA",
    "STATUS_PROCESSO",
    "STATUS_PAGAMENTO",
    "STATUS_CALCULO_MEDIAS",
    "MES_ANO_FATURAMENTO",
    "TCMP_JSON",
    "FCMP_JSON",
    "COLABORADORES_ENVOLVIDOS",
    "DATA_PRIMEIRO_PAGAMENTO",
    "DATA_ULTIMO_PAGAMENTO",
    "QUANTIDADE_PAGAMENTOS",
    "ULTIMA_ATUALIZACAO",
    "COMISSOES_ADIANTADAS_JSON",
    "STATUS_RECONCILIACAO",
    "OBSERVACOES",
]

# Valores padrão para criação de novo processo
VALORES_PADRAO_ESTADO = {
    "PROCESSO": "",
    "VALOR_TOTAL_PROCESSO": 0.0,
    "TOTAL_ANTECIPACOES": 0.0,
    "TOTAL_PAGAMENTOS_REGULARES": 0.0,
    "TOTAL_PAGO_ACUMULADO": 0.0,
    "SALDO_A_RECEBER": 0.0,
    "TOTAL_COMISSAO_ANTECIPACOES": 0.0,
    "TOTAL_COMISSAO_REGULARES": 0.0,
    "TOTAL_COMISSAO_ACUMULADA": 0.0,
    "STATUS_PROCESSO": "ORCAMENTO",
    "STATUS_PAGAMENTO": "PENDENTE",
    "STATUS_CALCULO_MEDIAS": "PENDENTE",
    "MES_ANO_FATURAMENTO": None,
    "TCMP_JSON": "{}",
    "FCMP_JSON": "{}",
    "COLABORADORES_ENVOLVIDOS": "",
    "DATA_PRIMEIRO_PAGAMENTO": None,
    "DATA_ULTIMO_PAGAMENTO": None,
    "QUANTIDADE_PAGAMENTOS": 0,
    "ULTIMA_ATUALIZACAO": None,
    "COMISSOES_ADIANTADAS_JSON": "{}",
    "STATUS_RECONCILIACAO": "PENDENTE",
    "OBSERVACOES": "",
}
